const express = require('express');
const router = express.Router();
const { check, validationResult } = require('express-validator');
const User = require("../models/User");
const jsonwebtoken = require('jsonwebtoken');
const constants = require('../config/constants.json');
const bcrypt = require('bcryptjs');
const auth = require('../routes/auth');
const controller = require('../controller/controller');


//http://localhost:8000/api/users

/*
    ROUTE: POST api/users
    DESC: Register a user
    ACCESS: Public
*/
router.post('/', [
    check('name', 'Please enter your name').notEmpty(),
    check('email', 'Please enter a valid email').isEmail(),
    check('email', 'Please use a UofT email').custom(value => {
        return value.includes("@mail.utoronto.ca");
    }),
    check('password', 'Please enter a password with 5 or more characters').isLength({min: 5})
], async (request, response) => { 
    const errorMessages = validationResult(request);
    if(!errorMessages.isEmpty()) return response.status(400).json({errors: errorMessages.array()});
    const {name, email, password} = request.body;
    try{
        let user = await User.findOne({email: email});
        if(user) return response.status(400).json({message: 'Email is already registered'});
        user = new User({
            name,
            email,
            password
        });
        const salt = await bcrypt.genSalt() //encrypt the password
        user.password = await bcrypt.hash(password, salt);
        await user.save();
        jsonwebtoken.sign(
            {user: { id: user.id}}, //user id is auto generated by mongoose
            constants.jsonwebtokenSecret, {
            expiresIn: 7200 //2 hours
        }, (error, token) => {
            if(error) throw error;
            response.json({token});
        });
    }catch(error){
        console.log(error.message);
        response.sendStatus(500); //server error
    }
}); 

/*
    ROUTE: DELETE api/users
    DESC: Delete a user
    ACCESS: Private
*/
//check controller.js for the delete function
router.delete('/', auth, controller.deleteUser);



module.exports = router;
